### PR TITLE
Added JavaScript_Todo_App

### PR DESCRIPTION
**Pull request by shobhit24**

### CODE REVIEW

**Comment by kerolloz** [comment]
Hello @shobhit24 
I see that you didn't use CockroachDB, did you?

**Comment by shobhit24** [comment]
> Hello @shobhit24
> I see that you didn't use CockroachDB, did you?

No

**Comment by kerolloz** [comment]
image
https://github.com/cockroachdb/cockroachdb-todo-apps#the-challenge

**Comment by Amruta-Ranade** [comment]
@shobhit24 Would you like to modify the app to use CockroachDB? If not, I'll have to mark the PR as invalid.

**Pull request closed without merging**
