### PR TITLE
django todo app

### PR DESCRIPTION
**Pull request by HeisenBug-07**

### CODE REVIEW

**Comment by Amruta-Ranade** [comment]
Does this use CockroachDB?

**Comment by HeisenBug-07** [comment]
no. 
i tried to learn but couldn't find any good tutorials

**Comment by Amruta-Ranade** [comment]
The challenge requires the use of CockroachDB. Feel free to use our docs for guidance to use CockroachDB: https://www.cockroachlabs.com/docs/v20.1/hello-world-example-apps.html

**Comment by HeisenBug-07** [comment]
thanks a lot mam

**Pull request closed without merging**
